add_library(log_interface INTERFACE)
target_include_directories(log_interface INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(log_interface INTERFACE hal_interface)
add_library(log_framework STATIC src/log.c src/log_backend_uart.c)
target_include_directories(log_framework PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
target_link_libraries(log_framework PUBLIC log_interface PRIVATE osal)
target_compile_definitions(log_framework PRIVATE $<$<CONFIG:Debug>:LOG_DEBUG_ENABLED>)
