#ifndef NX_LIFECYCLE_MODEL_CONFIG_H
#define NX_LIFECYCLE_MODEL_CONFIG_H
#define NX_CONFIG_STM32_FLASH_SIZE          1048576u
#define NX_CONFIG_STM32_NVIC_PRIORITY_GROUP 4
#define NX_CONFIG_STM32_SYSTICK_PRIORITY    15
#define NX_CONFIG_STM32_PENDSV_PRIORITY     15
#endif
