add_library(hal_interface INTERFACE)
target_include_directories(hal_interface INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(hal_interface INTERFACE nexus_build_options)
file(GLOB HAL_SOURCES CONFIGURE_DEPENDS "src/*.c")
add_library(hal STATIC ${HAL_SOURCES})
target_include_directories(hal PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
target_link_libraries(hal PUBLIC hal_interface PRIVATE osal nexus_arch)
