#ifndef NEXUS_CONFIG_H
#define NEXUS_CONFIG_H
#define NX_DEFINE_INSTANCE_STM32_GPIO(fn) fn(D, 12); fn(D, 13); fn(D, 14)
#define NX_CONFIG_GPIO_D12_MODE GPIO_MODE_INPUT
#define NX_CONFIG_GPIO_D12_PULL 0
#define NX_CONFIG_GPIO_D12_SPEED 0
#define NX_CONFIG_GPIO_D12_INIT_VALUE 0
#define NX_CONFIG_GPIO_D12_RW_MODE 0
#define NX_CONFIG_GPIO_D13_MODE GPIO_MODE_OUTPUT_PP
#define NX_CONFIG_GPIO_D13_PULL 0
#define NX_CONFIG_GPIO_D13_SPEED 0
#define NX_CONFIG_GPIO_D13_INIT_VALUE 0
#define NX_CONFIG_GPIO_D13_RW_MODE 1
#define NX_CONFIG_GPIO_D14_MODE GPIO_MODE_OUTPUT_PP
#define NX_CONFIG_GPIO_D14_PULL 0
#define NX_CONFIG_GPIO_D14_SPEED 0
#define NX_CONFIG_GPIO_D14_INIT_VALUE 0
#define NX_CONFIG_GPIO_D14_RW_MODE 2
#endif
