# Query validated resolved facts only. Source ownership stays in SoC CMake.
function(nexus_controller_modes output kind)
    file(READ "${NEXUS_CONFIG_DIR}/resolved.json" resolved)
    string(JSON count LENGTH "${resolved}" controllers)
    set(modes)
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON selected_kind GET "${resolved}"
                controllers ${index} kind)
            if(selected_kind STREQUAL kind)
                string(JSON mode GET "${resolved}" controllers ${index} mode)
                list(APPEND modes "${mode}")
            endif()
        endforeach()
    endif()
    list(REMOVE_DUPLICATES modes)
    set(${output} "${modes}" PARENT_SCOPE)
endfunction()
