add_library(nexus_build_options INTERFACE)
add_library(Nexus::Config ALIAS nexus_build_options)
target_include_directories(nexus_build_options INTERFACE "${NEXUS_CONFIG_DIR}")
target_compile_features(nexus_build_options INTERFACE c_std_11)
set_target_properties(nexus_build_options PROPERTIES
    NEXUS_SOURCE_DIR "${NEXUS_SOURCE_DIR}" NEXUS_CONFIG_DIR "${NEXUS_CONFIG_DIR}")
add_library(nexus_abi_options INTERFACE)
add_library(nexus_owned_warnings INTERFACE)
# The sole CPU resolver owns ABI combinations and optional instruction flags.
# CMake consumes the validated canonical list, never guesses an FPU or port.
if(NOT NEXUS_CPU_ARCH STREQUAL "native" AND
   NOT NEXUS_CPU_ARCH MATCHES "^cortex-m(0|0plus|3|4|7|23|33|55|85)$")
    message(FATAL_ERROR "Unsupported CPU architecture: ${NEXUS_CPU_ARCH}")
endif()
if(NOT DEFINED NEXUS_CPU_COMPILE_OPTIONS)
    message(FATAL_ERROR "Missing validated CPU compile options")
endif()
set(cpu ${NEXUS_CPU_COMPILE_OPTIONS})
if(NEXUS_CPU_ARCH STREQUAL "native")
    if(cpu OR NOT NEXUS_ENUM_ABI STREQUAL "native-int")
        message(FATAL_ERROR "Unsupported Native ABI contract")
    endif()
elseif(NOT cpu OR NOT NEXUS_ENUM_ABI STREQUAL "short-enums")
    message(FATAL_ERROR "Missing validated Cortex-M ABI contract")
endif()
if(MSVC)
    target_compile_options(nexus_owned_warnings INTERFACE /W4 /WX)
else()
    target_compile_options(nexus_owned_warnings INTERFACE
        -Wall -Wextra -Werror -Wpedantic -Wconversion -Wshadow
        "$<$<COMPILE_LANGUAGE:C>:-Wstrict-prototypes;-Wmissing-prototypes>")
endif()
string(REGEX REPLACE "-lto$" "" optimize "${NEXUS_OPTIMIZATION}")
if(NOT MSVC)
    target_compile_options(nexus_build_options INTERFACE "-${optimize}"
        -ffunction-sections -fdata-sections)
endif()
if(NEXUS_OPTIMIZATION MATCHES "-lto$")
    include(CheckIPOSupported)
    set(saved_exe_flags "${CMAKE_EXE_LINKER_FLAGS}")
    set(saved_c_flags "${CMAKE_C_FLAGS}")
    if(cpu)
        string(JOIN " " cpu_flags ${cpu})
        string(APPEND CMAKE_EXE_LINKER_FLAGS
            " ${cpu_flags} --specs=nano.specs --specs=nosys.specs")
        string(APPEND CMAKE_C_FLAGS
            " ${cpu_flags} --specs=nano.specs --specs=nosys.specs")
    endif()
    check_ipo_supported(RESULT ipo_supported OUTPUT ipo_error LANGUAGES C)
    set(CMAKE_EXE_LINKER_FLAGS "${saved_exe_flags}")
    set(CMAKE_C_FLAGS "${saved_c_flags}")
    if(NOT ipo_supported)
        message(FATAL_ERROR "Selected LTO is unsupported: ${ipo_error}")
    endif()
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
endif()
if(cpu)
    if(NOT CMAKE_CROSSCOMPILING OR NOT CMAKE_C_COMPILER MATCHES "arm-none-eabi")
        message(FATAL_ERROR "The selected MCU requires cmake/toolchains/arm-gcc.cmake")
    endif()
    target_compile_options(nexus_abi_options INTERFACE ${cpu})
    target_link_options(nexus_abi_options INTERFACE ${cpu})
    target_link_libraries(nexus_build_options INTERFACE nexus_abi_options)
    target_link_options(nexus_build_options INTERFACE ${cpu}
        --specs=nano.specs --specs=nosys.specs -nostartfiles -Wl,--gc-sections)
endif()
option(NEXUS_ENABLE_SANITIZERS "Host ASan/UBSan instrumentation" OFF)
option(NEXUS_ENABLE_THREAD_SANITIZER "Host ThreadSanitizer instrumentation" OFF)
if(NEXUS_ENABLE_SANITIZERS AND NEXUS_ENABLE_THREAD_SANITIZER)
    message(FATAL_ERROR "ASan/UBSan and ThreadSanitizer are mutually exclusive")
endif()
if(NEXUS_ENABLE_SANITIZERS OR NEXUS_ENABLE_THREAD_SANITIZER)
    if(NOT NEXUS_CPU_ARCH STREQUAL "native" OR
       NOT CMAKE_C_COMPILER_ID MATCHES "^(GNU|Clang)$")
        message(FATAL_ERROR "Sanitizers require the maintained native GCC/Clang model")
    endif()
endif()
if(NEXUS_ENABLE_SANITIZERS)
    target_compile_options(nexus_build_options INTERFACE
        -fsanitize=address,undefined -fno-omit-frame-pointer)
    target_link_options(nexus_build_options INTERFACE -fsanitize=address,undefined)
endif()
if(NEXUS_ENABLE_THREAD_SANITIZER)
    target_compile_options(nexus_build_options INTERFACE
        -fsanitize=thread -fno-omit-frame-pointer)
    target_link_options(nexus_build_options INTERFACE -fsanitize=thread)
endif()
