add_library(soc_gd32f470_interface INTERFACE)
target_include_directories(soc_gd32f470_interface INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}")
if(CONFIG_SERVICE_STORAGE)
    target_link_libraries(soc_gd32f470_interface INTERFACE nexus_storage)
endif()
add_library(soc_gd32f470 OBJECT clock.c interrupt.c identity.c)
if(CONFIG_SERVICE_STORAGE)
    target_sources(soc_gd32f470 PRIVATE flash.c)
endif()
target_link_libraries(soc_gd32f470 PRIVATE soc_gd32f470_interface sdk_gd32f4xx hal osal nexus_arch)
target_include_directories(soc_gd32f470 PRIVATE "${NEXUS_SOURCE_DIR}/platforms/gd32f470/include")
if(NEXUS_OSAL_BACKEND STREQUAL "freertos")
    target_link_libraries(soc_gd32f470 PRIVATE freertos_kernel freertos_config)
endif()
