add_library(soc_gd32f470_interface INTERFACE)
target_include_directories(soc_gd32f470_interface INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(soc_gd32f470_interface INTERFACE hal_interface)
add_library(soc_gd32f470 OBJECT clock.c interrupt.c identity.c flash.c)
target_link_libraries(soc_gd32f470 PRIVATE soc_gd32f470_interface sdk_gd32f4xx Nexus::HALProviders hal_support osal nexus_arch)
target_include_directories(soc_gd32f470 PRIVATE "${NEXUS_SOURCE_DIR}/platforms/gd32f470/include")
if(NEXUS_OSAL_BACKEND STREQUAL "freertos")
    target_link_libraries(soc_gd32f470 PRIVATE freertos_kernel freertos_config)
endif()
