# Private firmware assembly rule. Referencing component objects as interface
# link items retains registration records and strong callbacks in every image.
function(nexus_stm32_forward_components assembly)
    get_target_property(assembly_type "${assembly}" TYPE)
    if(NOT assembly_type STREQUAL "OBJECT_LIBRARY")
        message(FATAL_ERROR "STM32 assembly ${assembly} must be an OBJECT library")
    endif()
    foreach(component IN LISTS ARGN)
        get_target_property(component_type "${component}" TYPE)
        if(NOT component_type STREQUAL "OBJECT_LIBRARY")
            message(FATAL_ERROR "STM32 assembly component ${component} must be an OBJECT library")
        endif()
        target_link_libraries("${assembly}" INTERFACE "$<TARGET_OBJECTS:${component}>")
    endforeach()
endfunction()
