#ifndef NEXUS_CONFIG_H
#define NEXUS_CONFIG_H
#define NX_CONFIG_STM32_UART_DEFAULT_WORD_LENGTH 0
#define NX_CONFIG_STM32_UART_DEFAULT_STOP_BITS 0
#define NX_CONFIG_STM32_UART_DEFAULT_PARITY 0
#define NX_CONFIG_STM32_UART_BUFFER_OVERFLOW_POLICY 1
#define NX_DEFINE_INSTANCE_STM32_UART(fn) fn(0); fn(1); fn(2)
#define NX_CONFIG_STM32_UART0_BAUDRATE 9600
#define NX_CONFIG_STM32_UART0_TX_BUFFER_SIZE 8
#define NX_CONFIG_STM32_UART0_RX_BUFFER_SIZE 4
#define NX_CONFIG_STM32_UART1_BAUDRATE 115200
#define NX_CONFIG_STM32_UART1_TX_BUFFER_SIZE 8
#define NX_CONFIG_STM32_UART1_RX_BUFFER_SIZE 4
#define NX_CONFIG_STM32_UART2_BAUDRATE 19200
#define NX_CONFIG_STM32_UART2_TX_BUFFER_SIZE 8
#define NX_CONFIG_STM32_UART2_RX_BUFFER_SIZE 4
#endif
