include_guard(GLOBAL)

# The source fragment is input only. Every consumer reads the resolved build bundle.
macro(nexus_configure)
    if(NOT NEXUS_CONFIG_FILE)
        if(NEXUS_PLATFORM STREQUAL "native")
            set(NEXUS_CONFIG_FILE "${NEXUS_SOURCE_DIR}/platforms/native/defconfig")
        elseif(NEXUS_PLATFORM STREQUAL "stm32")
            set(NEXUS_CONFIG_FILE "${NEXUS_SOURCE_DIR}/configs/stm32f407_baremetal_defconfig")
        else()
            message(FATAL_ERROR "Select an implemented platform and explicit NEXUS_CONFIG_FILE")
        endif()
    endif()
    if(NOT EXISTS "${NEXUS_CONFIG_FILE}")
        message(FATAL_ERROR "Configuration fragment missing: ${NEXUS_CONFIG_FILE}")
    endif()
    foreach(_legacy NEXUS_CONFIG_HEADER NEXUS_TOOLCHAIN_NAME NEXUS_CPU_ARCH NEXUS_FPU_TYPE NEXUS_FLOAT_ABI NEXUS_LINKER_SCRIPT)
        unset(${_legacy} CACHE)
    endforeach()
    set(NEXUS_CONFIG_DIR "${NEXUS_BINARY_DIR}/generated")
    set(NEXUS_CONFIG_HEADER "${NEXUS_CONFIG_DIR}/nexus_config.h")
    file(MAKE_DIRECTORY "${NEXUS_CONFIG_DIR}")
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
        if(CMAKE_CROSSCOMPILING)
            set(_nexus_toolchain TOOLCHAIN_ARM_GCC)
        else()
            set(_nexus_toolchain TOOLCHAIN_GCC)
        endif()
    elseif(CMAKE_C_COMPILER_ID MATCHES "Clang")
        set(_nexus_toolchain TOOLCHAIN_CLANG)
    elseif(MSVC)
        set(_nexus_toolchain TOOLCHAIN_MSVC)
    else()
        message(FATAL_ERROR "Compiler not supported by the maintained configuration")
    endif()
    string(TOUPPER "${CMAKE_BUILD_TYPE}" _nexus_mode)
    if(NOT _nexus_mode MATCHES "^(DEBUG|RELEASE|MINSIZEREL|RELWITHDEBINFO)$")
        message(FATAL_ERROR "Select a supported CMAKE_BUILD_TYPE in the preset")
    endif()
    if(CMAKE_CONFIGURATION_TYPES)
        # One build directory owns one effective configuration, including mode.
        # A different mode requires a different preset/output directory.
        if(PROJECT_IS_TOP_LEVEL)
            set(CMAKE_CONFIGURATION_TYPES "${CMAKE_BUILD_TYPE}" CACHE STRING "Resolved build mode" FORCE)
        elseif(NOT CMAKE_CONFIGURATION_TYPES STREQUAL CMAKE_BUILD_TYPE)
            message(FATAL_ERROR "An embedded Nexus build requires one parent-selected configuration matching CMAKE_BUILD_TYPE")
        endif()
    endif()
    set(_nexus_settings --set "BUILD_TYPE_${_nexus_mode}=y" --set "${_nexus_toolchain}=y")
    foreach(_nexus_pair "BUILD_TESTS;NEXUS_BUILD_TESTS" "BUILD_EXAMPLES;NEXUS_BUILD_EXAMPLES" "ENABLE_COVERAGE;NEXUS_ENABLE_COVERAGE" "ENABLE_SANITIZERS;NEXUS_ENABLE_SANITIZERS")
        list(GET _nexus_pair 0 _nexus_symbol)
        list(GET _nexus_pair 1 _nexus_option)
        if(${_nexus_option})
            list(APPEND _nexus_settings --set "${_nexus_symbol}=y")
        else()
            list(APPEND _nexus_settings --set "${_nexus_symbol}=n")
        endif()
    endforeach()
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${NEXUS_SOURCE_DIR}/scripts/kconfig/generate_config.py"
        --kconfig "${NEXUS_SOURCE_DIR}/Kconfig" --config "${NEXUS_CONFIG_FILE}"
        --output "${NEXUS_CONFIG_HEADER}" --effective-config "${NEXUS_CONFIG_DIR}/effective.config"
        --cmake-output "${NEXUS_CONFIG_DIR}/config.cmake" ${_nexus_settings}
        WORKING_DIRECTORY "${NEXUS_SOURCE_DIR}" RESULT_VARIABLE _nexus_result
        OUTPUT_VARIABLE _nexus_output ERROR_VARIABLE _nexus_error)
    if(NOT _nexus_result EQUAL 0)
        message(FATAL_ERROR "Kconfig generation failed (${_nexus_result}):\n${_nexus_error}")
    endif()
    # Retire old Nexus cache values without deleting another project's symbols.
    file(STRINGS "${NEXUS_CONFIG_DIR}/config.cmake" _nexus_entries REGEX "^set\\(CONFIG_")
    set(_nexus_symbols)
    foreach(_nexus_entry IN LISTS _nexus_entries)
        string(REGEX REPLACE "^set\\((CONFIG_[A-Za-z0-9_]+).*" "\\1" _nexus_symbol "${_nexus_entry}")
        list(APPEND _nexus_symbols "${_nexus_symbol}")
    endforeach()
    get_cmake_property(_nexus_cache CACHE_VARIABLES)
    foreach(_nexus_variable IN LISTS _nexus_cache)
        if(_nexus_variable MATCHES "^CONFIG_" AND
           (PROJECT_IS_TOP_LEVEL OR _nexus_variable IN_LIST _nexus_symbols))
            unset(${_nexus_variable} CACHE)
        endif()
    endforeach()
    include("${NEXUS_CONFIG_DIR}/config.cmake")
    if(NOT CONFIG_PLATFORM_NAME STREQUAL NEXUS_PLATFORM)
        message(FATAL_ERROR "Platform conflict: preset ${NEXUS_PLATFORM}, config ${CONFIG_PLATFORM_NAME}")
    endif()
    if(NEXUS_OSAL_BACKEND AND NOT NEXUS_OSAL_BACKEND STREQUAL CONFIG_OSAL_BACKEND_NAME)
        message(FATAL_ERROR "OSAL backend conflict: ${NEXUS_OSAL_BACKEND} != ${CONFIG_OSAL_BACKEND_NAME}")
    endif()
    set(NEXUS_OSAL_BACKEND "${CONFIG_OSAL_BACKEND_NAME}")
    file(GLOB_RECURSE _nexus_kconfigs CONFIGURE_DEPENDS "${NEXUS_SOURCE_DIR}/*Kconfig*")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        ${_nexus_kconfigs} "${NEXUS_CONFIG_FILE}" "${NEXUS_SOURCE_DIR}/scripts/kconfig/generate_config.py")
endmacro()
