##############################################################################
# NexusIncremental.cmake - Incremental Build Module
##############################################################################
#
# NexusIncremental.cmake
# Incremental build system with dependency tracking
# Author: Nexus Team
#
# This module provides incremental build functionality including:
# - Dependency file generation (.d files)
# - Indirect dependency tracking
# - Hash-based change detection
# - Incremental compilation logic
# - Incremental linking
#
##############################################################################

include_guard(GLOBAL)

##############################################################################
# Global Variables
##############################################################################

# Dependency tracking database directory
set(NEXUS_DEP_DB_DIR "${CMAKE_BINARY_DIR}/.nexus/deps" CACHE PATH
    "Directory for dependency tracking database")

# Hash cache directory
set(NEXUS_HASH_CACHE_DIR "${CMAKE_BINARY_DIR}/.nexus/hashes" CACHE PATH
    "Directory for file hash cache")

# Create directories if they don't exist
file(MAKE_DIRECTORY "${NEXUS_DEP_DB_DIR}")
file(MAKE_DIRECTORY "${NEXUS_HASH_CACHE_DIR}")

##############################################################################
# Dependency File Generation (Task 9.1)
##############################################################################

#
# Enable dependency file generation for target
# TARGET: Target name
#
# Configures compiler to generate .d dependency files
#                  and sets up dependency tracking infrastructure
#
function(nexus_enable_dependency_tracking TARGET)
    # Validate target
    if(NOT TARGET ${TARGET})
        message(FATAL_ERROR "Target does not exist: ${TARGET}")
    endif()

    # Enable dependency file generation for GCC/Clang
    if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
        target_compile_options(${TARGET} PRIVATE
            -MMD    # Generate dependency files
            -MP     # Add phony targets for headers
            -MF     # Specify output file (handled by CMake)
        )
    elseif(CMAKE_C_COMPILER_ID MATCHES "MSVC")
        # MSVC uses /showIncludes
        target_compile_options(${TARGET} PRIVATE
            /showIncludes
        )
    endif()

    # Set CMake properties for dependency tracking
    set_target_properties(${TARGET} PROPERTIES
        C_DEPENDENCY_FILE_GENERATION ON
        CXX_DEPENDENCY_FILE_GENERATION ON
    )

    # Create target-specific dependency directory
    set(TARGET_DEP_DIR "${NEXUS_DEP_DB_DIR}/${TARGET}")
    file(MAKE_DIRECTORY "${TARGET_DEP_DIR}")

    # Store dependency directory in target property
    set_target_properties(${TARGET} PROPERTIES
        NEXUS_DEP_DIR "${TARGET_DEP_DIR}"
    )

    message(STATUS "Enabled dependency tracking for: ${TARGET}")
endfunction()

#
# Parse dependency file (.d) and extract dependencies
# DEP_FILE: Path to .d file
# DEPS_VAR: Variable to store list of dependencies
#
# Parses Makefile-style dependency files generated by
#                  the compiler and extracts the list of header files
#
function(nexus_parse_dependency_file DEP_FILE DEPS_VAR)
    if(NOT EXISTS "${DEP_FILE}")
        set(${DEPS_VAR} "" PARENT_SCOPE)
        return()
    endif()

    # Read dependency file
    file(READ "${DEP_FILE}" DEP_CONTENT)

    # Remove line continuations (backslash + newline)
    string(REPLACE "\\\n" " " DEP_CONTENT "${DEP_CONTENT}")
    string(REPLACE "\\\r\n" " " DEP_CONTENT "${DEP_CONTENT}")

    # Extract dependencies (everything after the colon)
    string(REGEX REPLACE "^[^:]+: " "" DEP_CONTENT "${DEP_CONTENT}")

    # Split into list
    string(REGEX REPLACE "[ \t\r\n]+" ";" DEP_LIST "${DEP_CONTENT}")

    # Remove empty entries
    list(REMOVE_ITEM DEP_LIST "")

    # Normalize paths
    set(NORMALIZED_DEPS "")
    foreach(DEP ${DEP_LIST})
        get_filename_component(ABS_DEP "${DEP}" ABSOLUTE)
        list(APPEND NORMALIZED_DEPS "${ABS_DEP}")
    endforeach()

    # Remove duplicates
    list(REMOVE_DUPLICATES NORMALIZED_DEPS)

    set(${DEPS_VAR} "${NORMALIZED_DEPS}" PARENT_SCOPE)
endfunction()

#
# Build dependency graph for target
# TARGET: Target name
# GRAPH_VAR: Variable to store dependency graph (JSON)
#
# Scans all .d files for target and builds a complete
#                  dependency graph showing which source files depend on
#                  which header files
#
function(nexus_build_dependency_graph TARGET GRAPH_VAR)
    # Validate target
    if(NOT TARGET ${TARGET})
        message(FATAL_ERROR "Target does not exist: ${TARGET}")
    endif()

    # Get target sources
    get_target_property(SOURCES ${TARGET} SOURCES)
    if(NOT SOURCES)
        set(${GRAPH_VAR} "{}" PARENT_SCOPE)
        return()
    endif()

    # Get dependency directory
    get_target_property(DEP_DIR ${TARGET} NEXUS_DEP_DIR)
    if(NOT DEP_DIR)
        set(DEP_DIR "${NEXUS_DEP_DB_DIR}/${TARGET}")
    endif()

    # Build graph
    set(GRAPH_JSON "{")
    set(FIRST_ENTRY TRUE)

    foreach(SOURCE ${SOURCES})
        # Get absolute path
        get_filename_component(ABS_SOURCE "${SOURCE}" ABSOLUTE)

        # Determine .d file path
        get_filename_component(SOURCE_NAME "${SOURCE}" NAME)
        set(DEP_FILE "${DEP_DIR}/${SOURCE_NAME}.d")

        # Parse dependency file
        nexus_parse_dependency_file("${DEP_FILE}" DEPS)

        # Add to graph
        if(NOT FIRST_ENTRY)
            string(APPEND GRAPH_JSON ",")
        endif()
        set(FIRST_ENTRY FALSE)

        string(APPEND GRAPH_JSON "\n  \"${ABS_SOURCE}\": [")

        set(FIRST_DEP TRUE)
        foreach(DEP ${DEPS})
            if(NOT FIRST_DEP)
                string(APPEND GRAPH_JSON ", ")
            endif()
            set(FIRST_DEP FALSE)
            string(APPEND GRAPH_JSON "\"${DEP}\"")
        endforeach()

        string(APPEND GRAPH_JSON "]")
    endforeach()

    string(APPEND GRAPH_JSON "\n}")

    set(${GRAPH_VAR} "${GRAPH_JSON}" PARENT_SCOPE)
endfunction()

#
# Save dependency graph to file
# TARGET: Target name
# OUTPUT_FILE: Output JSON file path
#
function(nexus_save_dependency_graph TARGET OUTPUT_FILE)
    # Build dependency graph
    nexus_build_dependency_graph(${TARGET} GRAPH_JSON)

    # Write to file
    file(WRITE "${OUTPUT_FILE}" "${GRAPH_JSON}")

    message(STATUS "Saved dependency graph for ${TARGET}: ${OUTPUT_FILE}")
endfunction()

##############################################################################
# Indirect Dependency Tracking (Task 9.3)
##############################################################################

#
# Recursively resolve indirect dependencies
# HEADER_FILE: Header file to analyze
# VISITED_VAR: Set of already visited headers
# DEPS_VAR: Variable to store all dependencies
#
# Recursively parses header files to find all indirect
#                  dependencies (headers included by headers)
#
function(nexus_resolve_indirect_dependencies HEADER_FILE VISITED_VAR DEPS_VAR)
    # Get current visited set
    set(VISITED ${${VISITED_VAR}})
    set(ALL_DEPS ${${DEPS_VAR}})

    # Check if already visited
    list(FIND VISITED "${HEADER_FILE}" FOUND_IDX)
    if(NOT FOUND_IDX EQUAL -1)
        return()
    endif()

    # Mark as visited
    list(APPEND VISITED "${HEADER_FILE}")

    # Add to dependencies
    list(APPEND ALL_DEPS "${HEADER_FILE}")

    # Check if file exists
    if(NOT EXISTS "${HEADER_FILE}")
        set(${VISITED_VAR} "${VISITED}" PARENT_SCOPE)
        set(${DEPS_VAR} "${ALL_DEPS}" PARENT_SCOPE)
        return()
    endif()

    # Read header file
    file(READ "${HEADER_FILE}" HEADER_CONTENT)

    # Find all #include directives
    string(REGEX MATCHALL "#[ \t]*include[ \t]+[\"<]([^\">]+)[\">]"
           INCLUDES "${HEADER_CONTENT}")

    # Get header directory for relative includes
    get_filename_component(HEADER_DIR "${HEADER_FILE}" DIRECTORY)

    # Process each include
    foreach(INCLUDE_LINE ${INCLUDES})
        # Extract included file name
        string(REGEX REPLACE "#[ \t]*include[ \t]+[\"<]([^\">]+)[\">]" "\\1"
               INCLUDED_FILE "${INCLUDE_LINE}")

        # Try to resolve path
        set(RESOLVED_PATH "")

        # First try relative to current header
        if(EXISTS "${HEADER_DIR}/${INCLUDED_FILE}")
            get_filename_component(RESOLVED_PATH
                "${HEADER_DIR}/${INCLUDED_FILE}" ABSOLUTE)
        else()
            # Try to find in include paths (simplified - would need full search)
            # For now, just check if it's an absolute path
            if(EXISTS "${INCLUDED_FILE}")
                get_filename_component(RESOLVED_PATH "${INCLUDED_FILE}" ABSOLUTE)
            endif()
        endif()

        # Recursively process if found
        if(RESOLVED_PATH)
            nexus_resolve_indirect_dependencies(
                "${RESOLVED_PATH}" VISITED ALL_DEPS)
        endif()
    endforeach()

    # Update parent scope
    set(${VISITED_VAR} "${VISITED}" PARENT_SCOPE)
    set(${DEPS_VAR} "${ALL_DEPS}" PARENT_SCOPE)
endfunction()

#
# Get all dependencies (direct + indirect) for source file
# SOURCE_FILE: Source file path
# TARGET: Target name (for .d file lookup)
# DEPS_VAR: Variable to store all dependencies
#
function(nexus_get_all_dependencies SOURCE_FILE TARGET DEPS_VAR)
    # Get dependency directory
    get_target_property(DEP_DIR ${TARGET} NEXUS_DEP_DIR)
    if(NOT DEP_DIR)
        set(DEP_DIR "${NEXUS_DEP_DB_DIR}/${TARGET}")
    endif()

    # Get .d file
    get_filename_component(SOURCE_NAME "${SOURCE_FILE}" NAME)
    set(DEP_FILE "${DEP_DIR}/${SOURCE_NAME}.d")

    # Parse direct dependencies
    nexus_parse_dependency_file("${DEP_FILE}" DIRECT_DEPS)

    # Resolve indirect dependencies for each direct dependency
    set(ALL_DEPS "")
    set(VISITED "")

    foreach(HEADER ${DIRECT_DEPS})
        nexus_resolve_indirect_dependencies("${HEADER}" VISITED ALL_DEPS)
    endforeach()

    # Remove duplicates
    list(REMOVE_DUPLICATES ALL_DEPS)

    set(${DEPS_VAR} "${ALL_DEPS}" PARENT_SCOPE)
endfunction()

#
# Update dependency graph with indirect dependencies
# TARGET: Target name
#
function(nexus_update_dependency_graph TARGET)
    # Get target sources
    get_target_property(SOURCES ${TARGET} SOURCES)
    if(NOT SOURCES)
        return()
    endif()

    # Get dependency directory
    get_target_property(DEP_DIR ${TARGET} NEXUS_DEP_DIR)
    if(NOT DEP_DIR)
        set(DEP_DIR "${NEXUS_DEP_DB_DIR}/${TARGET}")
    endif()

    # Update graph file
    set(GRAPH_FILE "${DEP_DIR}/dependency_graph.json")

    # Build complete graph with indirect dependencies
    set(GRAPH_JSON "{")
    set(FIRST_ENTRY TRUE)

    foreach(SOURCE ${SOURCES})
        get_filename_component(ABS_SOURCE "${SOURCE}" ABSOLUTE)

        # Get all dependencies (direct + indirect)
        nexus_get_all_dependencies("${SOURCE}" ${TARGET} ALL_DEPS)

        # Add to graph
        if(NOT FIRST_ENTRY)
            string(APPEND GRAPH_JSON ",")
        endif()
        set(FIRST_ENTRY FALSE)

        string(APPEND GRAPH_JSON "\n  \"${ABS_SOURCE}\": [")

        set(FIRST_DEP TRUE)
        foreach(DEP ${ALL_DEPS})
            if(NOT FIRST_DEP)
                string(APPEND GRAPH_JSON ", ")
            endif()
            set(FIRST_DEP FALSE)
            string(APPEND GRAPH_JSON "\"${DEP}\"")
        endforeach()

        string(APPEND GRAPH_JSON "]")
    endforeach()

    string(APPEND GRAPH_JSON "\n}")

    # Write to file
    file(WRITE "${GRAPH_FILE}" "${GRAPH_JSON}")

    message(STATUS "Updated dependency graph for ${TARGET}")
endfunction()


##############################################################################
# Hash-Based Change Detection (Task 9.5)
##############################################################################

#
# Calculate SHA-256 hash of file content
# FILE_PATH: Path to file
# HASH_VAR: Variable to store hash
#
function(nexus_calculate_file_hash FILE_PATH HASH_VAR)
    if(NOT EXISTS "${FILE_PATH}")
        set(${HASH_VAR} "" PARENT_SCOPE)
        return()
    endif()

    # Calculate SHA-256 hash
    file(SHA256 "${FILE_PATH}" FILE_HASH)

    set(${HASH_VAR} "${FILE_HASH}" PARENT_SCOPE)
endfunction()

#
# Get cached hash for file
# FILE_PATH: Path to file
# HASH_VAR: Variable to store cached hash
#
function(nexus_get_cached_hash FILE_PATH HASH_VAR)
    # Normalize path for cache key
    get_filename_component(ABS_PATH "${FILE_PATH}" ABSOLUTE)
    string(SHA256 PATH_HASH "${ABS_PATH}")

    # Cache file path
    set(CACHE_FILE "${NEXUS_HASH_CACHE_DIR}/${PATH_HASH}.txt")

    # Read cached hash if exists
    if(EXISTS "${CACHE_FILE}")
        file(READ "${CACHE_FILE}" CACHED_HASH)
        string(STRIP "${CACHED_HASH}" CACHED_HASH)
        set(${HASH_VAR} "${CACHED_HASH}" PARENT_SCOPE)
    else()
        set(${HASH_VAR} "" PARENT_SCOPE)
    endif()
endfunction()

#
# Update cached hash for file
# FILE_PATH: Path to file
# HASH: Hash value to cache
#
function(nexus_update_cached_hash FILE_PATH HASH)
    # Normalize path for cache key
    get_filename_component(ABS_PATH "${FILE_PATH}" ABSOLUTE)
    string(SHA256 PATH_HASH "${ABS_PATH}")

    # Cache file path
    set(CACHE_FILE "${NEXUS_HASH_CACHE_DIR}/${PATH_HASH}.txt")

    # Write hash to cache
    file(WRITE "${CACHE_FILE}" "${HASH}")
endfunction()

#
# Check if file has changed using content hash
# FILE_PATH: Path to file
# CHANGED_VAR: Variable to store result (TRUE/FALSE)
#
# Compares current file hash with cached hash to detect
#                  changes. More accurate than timestamp-based detection.
#
function(nexus_file_has_changed FILE_PATH CHANGED_VAR)
    if(NOT EXISTS "${FILE_PATH}")
        set(${CHANGED_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    # Calculate current hash
    nexus_calculate_file_hash("${FILE_PATH}" CURRENT_HASH)

    # Get cached hash
    nexus_get_cached_hash("${FILE_PATH}" CACHED_HASH)

    # Compare hashes
    if(NOT CACHED_HASH OR NOT CURRENT_HASH STREQUAL CACHED_HASH)
        set(${CHANGED_VAR} TRUE PARENT_SCOPE)
        # Update cache
        nexus_update_cached_hash("${FILE_PATH}" "${CURRENT_HASH}")
    else()
        set(${CHANGED_VAR} FALSE PARENT_SCOPE)
    endif()
endfunction()

#
# Check if any dependency has changed
# SOURCE_FILE: Source file path
# TARGET: Target name
# CHANGED_VAR: Variable to store result (TRUE/FALSE)
#
function(nexus_dependencies_have_changed SOURCE_FILE TARGET CHANGED_VAR)
    # Check if source file itself changed
    nexus_file_has_changed("${SOURCE_FILE}" SOURCE_CHANGED)
    if(SOURCE_CHANGED)
        set(${CHANGED_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    # Get all dependencies
    nexus_get_all_dependencies("${SOURCE_FILE}" ${TARGET} ALL_DEPS)

    # Check each dependency
    foreach(DEP ${ALL_DEPS})
        nexus_file_has_changed("${DEP}" DEP_CHANGED)
        if(DEP_CHANGED)
            set(${CHANGED_VAR} TRUE PARENT_SCOPE)
            return()
        endif()
    endforeach()

    # No changes detected
    set(${CHANGED_VAR} FALSE PARENT_SCOPE)
endfunction()

#
# Clear hash cache
# PATTERN: Optional glob pattern to match files
#
function(nexus_clear_hash_cache)
    cmake_parse_arguments(ARG "" "PATTERN" "" ${ARGN})

    if(ARG_PATTERN)
        file(GLOB CACHE_FILES "${NEXUS_HASH_CACHE_DIR}/${ARG_PATTERN}")
        foreach(CACHE_FILE ${CACHE_FILES})
            file(REMOVE "${CACHE_FILE}")
        endforeach()
        message(STATUS "Cleared hash cache matching: ${ARG_PATTERN}")
    else()
        file(REMOVE_RECURSE "${NEXUS_HASH_CACHE_DIR}")
        file(MAKE_DIRECTORY "${NEXUS_HASH_CACHE_DIR}")
        message(STATUS "Cleared all hash cache")
    endif()
endfunction()

##############################################################################
# Incremental Compilation Logic (Task 9.7)
##############################################################################

#
# Determine if source file needs recompilation
# SOURCE_FILE: Source file path
# OBJECT_FILE: Object file path
# TARGET: Target name
# REBUILD_VAR: Variable to store result (TRUE/FALSE)
#
# Implements the change detection algorithm:
#                  1. Check if object file exists
#                  2. Check if source file content changed (hash)
#                  3. Check if any dependency changed (hash)
#                  4. Check if compile flags changed
#                  5. Check if compiler version changed
#
function(nexus_should_rebuild SOURCE_FILE OBJECT_FILE TARGET REBUILD_VAR)
    # 1. Object file doesn't exist
    if(NOT EXISTS "${OBJECT_FILE}")
        set(${REBUILD_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    # 2. Source file or dependencies changed
    nexus_dependencies_have_changed("${SOURCE_FILE}" ${TARGET} DEPS_CHANGED)
    if(DEPS_CHANGED)
        set(${REBUILD_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    # 3. Compile flags changed (simplified check)
    # In a full implementation, would compare cached flags with current flags
    get_target_property(COMPILE_OPTIONS ${TARGET} COMPILE_OPTIONS)
    get_target_property(COMPILE_DEFINITIONS ${TARGET} COMPILE_DEFINITIONS)

    # Create flags signature
    set(FLAGS_SIGNATURE "${COMPILE_OPTIONS};${COMPILE_DEFINITIONS}")
    string(SHA256 FLAGS_HASH "${FLAGS_SIGNATURE}")

    # Check cached flags
    get_filename_component(SOURCE_NAME "${SOURCE_FILE}" NAME)
    set(FLAGS_CACHE_FILE "${NEXUS_HASH_CACHE_DIR}/${TARGET}_${SOURCE_NAME}_flags.txt")

    if(EXISTS "${FLAGS_CACHE_FILE}")
        file(READ "${FLAGS_CACHE_FILE}" CACHED_FLAGS_HASH)
        string(STRIP "${CACHED_FLAGS_HASH}" CACHED_FLAGS_HASH)

        if(NOT FLAGS_HASH STREQUAL CACHED_FLAGS_HASH)
            # Flags changed
            file(WRITE "${FLAGS_CACHE_FILE}" "${FLAGS_HASH}")
            set(${REBUILD_VAR} TRUE PARENT_SCOPE)
            return()
        endif()
    else()
        # No cached flags, assume rebuild needed
        file(WRITE "${FLAGS_CACHE_FILE}" "${FLAGS_HASH}")
        set(${REBUILD_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    # 4. Compiler version changed (simplified check)
    set(COMPILER_SIGNATURE "${CMAKE_C_COMPILER};${CMAKE_C_COMPILER_VERSION}")
    string(SHA256 COMPILER_HASH "${COMPILER_SIGNATURE}")

    set(COMPILER_CACHE_FILE "${NEXUS_HASH_CACHE_DIR}/compiler_version.txt")

    if(EXISTS "${COMPILER_CACHE_FILE}")
        file(READ "${COMPILER_CACHE_FILE}" CACHED_COMPILER_HASH)
        string(STRIP "${CACHED_COMPILER_HASH}" CACHED_COMPILER_HASH)

        if(NOT COMPILER_HASH STREQUAL CACHED_COMPILER_HASH)
            # Compiler changed - rebuild everything
            file(WRITE "${COMPILER_CACHE_FILE}" "${COMPILER_HASH}")
            set(${REBUILD_VAR} TRUE PARENT_SCOPE)
            return()
        endif()
    else()
        file(WRITE "${COMPILER_CACHE_FILE}" "${COMPILER_HASH}")
        set(${REBUILD_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    # No rebuild needed
    set(${REBUILD_VAR} FALSE PARENT_SCOPE)
endfunction()

#
# Get list of sources that need recompilation
# TARGET: Target name
# SOURCES_VAR: Variable to store list of sources
#
function(nexus_get_sources_to_rebuild TARGET SOURCES_VAR)
    # Get target sources
    get_target_property(SOURCES ${TARGET} SOURCES)
    if(NOT SOURCES)
        set(${SOURCES_VAR} "" PARENT_SCOPE)
        return()
    endif()

    # Get target binary directory
    get_target_property(BINARY_DIR ${TARGET} BINARY_DIR)
    if(NOT BINARY_DIR)
        set(BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}")
    endif()

    # Check each source
    set(REBUILD_SOURCES "")

    foreach(SOURCE ${SOURCES})
        get_filename_component(ABS_SOURCE "${SOURCE}" ABSOLUTE)
        get_filename_component(SOURCE_NAME "${SOURCE}" NAME_WE)

        # Determine object file path
        set(OBJECT_FILE "${BINARY_DIR}/CMakeFiles/${TARGET}.dir/${SOURCE_NAME}.c.o")

        # Check if rebuild needed
        nexus_should_rebuild("${ABS_SOURCE}" "${OBJECT_FILE}" ${TARGET} REBUILD)

        if(REBUILD)
            list(APPEND REBUILD_SOURCES "${ABS_SOURCE}")
        endif()
    endforeach()

    set(${SOURCES_VAR} "${REBUILD_SOURCES}" PARENT_SCOPE)
endfunction()

#
# Enable incremental compilation for target
# TARGET: Target name
#
# Configures target for incremental compilation with
#                  hash-based change detection
#
function(nexus_enable_incremental_build TARGET)
    # Enable dependency tracking first
    nexus_enable_dependency_tracking(${TARGET})

    # Set target property to mark incremental build enabled
    set_target_properties(${TARGET} PROPERTIES
        NEXUS_INCREMENTAL_BUILD ON
    )

    message(STATUS "Enabled incremental build for: ${TARGET}")
endfunction()

##############################################################################
# Incremental Linking (Task 9.9)
##############################################################################

#
# Check if target needs relinking
# TARGET: Target name
# RELINK_VAR: Variable to store result (TRUE/FALSE)
#
# Determines if executable/library needs relinking based on:
#                  1. Any object file changed
#                  2. Any dependency library changed
#                  3. Link flags changed
#
function(nexus_should_relink TARGET RELINK_VAR)
    # Get target file
    get_target_property(TARGET_FILE ${TARGET} LOCATION)
    if(NOT TARGET_FILE)
        set(${RELINK_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    # Check if target file exists
    if(NOT EXISTS "${TARGET_FILE}")
        set(${RELINK_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    # Check if any source needs recompilation
    nexus_get_sources_to_rebuild(${TARGET} REBUILD_SOURCES)
    if(REBUILD_SOURCES)
        set(${RELINK_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    # Check if any dependency library changed
    get_target_property(LINK_LIBRARIES ${TARGET} LINK_LIBRARIES)
    if(LINK_LIBRARIES)
        foreach(LIB ${LINK_LIBRARIES})
            if(TARGET ${LIB})
                # Get library file
                get_target_property(LIB_FILE ${LIB} LOCATION)
                if(LIB_FILE AND EXISTS "${LIB_FILE}")
                    # Check if library changed
                    nexus_file_has_changed("${LIB_FILE}" LIB_CHANGED)
                    if(LIB_CHANGED)
                        set(${RELINK_VAR} TRUE PARENT_SCOPE)
                        return()
                    endif()
                endif()
            endif()
        endforeach()
    endif()

    # Check if link flags changed
    get_target_property(LINK_OPTIONS ${TARGET} LINK_OPTIONS)
    set(LINK_SIGNATURE "${LINK_OPTIONS}")
    string(SHA256 LINK_HASH "${LINK_SIGNATURE}")

    set(LINK_CACHE_FILE "${NEXUS_HASH_CACHE_DIR}/${TARGET}_link_flags.txt")

    if(EXISTS "${LINK_CACHE_FILE}")
        file(READ "${LINK_CACHE_FILE}" CACHED_LINK_HASH)
        string(STRIP "${CACHED_LINK_HASH}" CACHED_LINK_HASH)

        if(NOT LINK_HASH STREQUAL CACHED_LINK_HASH)
            file(WRITE "${LINK_CACHE_FILE}" "${LINK_HASH}")
            set(${RELINK_VAR} TRUE PARENT_SCOPE)
            return()
        endif()
    else()
        file(WRITE "${LINK_CACHE_FILE}" "${LINK_HASH}")
        set(${RELINK_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    # No relinking needed
    set(${RELINK_VAR} FALSE PARENT_SCOPE)
endfunction()

#
# Enable incremental linking for target
# TARGET: Target name
#
# Configures target for incremental linking
#                  Note: Actual incremental linking support depends on linker
#
function(nexus_enable_incremental_linking TARGET)
    # Check if target is executable or library
    get_target_property(TARGET_TYPE ${TARGET} TYPE)

    if(NOT TARGET_TYPE MATCHES "EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY")
        message(WARNING "Incremental linking only supported for executables and libraries")
        return()
    endif()

    # Enable incremental linking flags for supported linkers
    if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        # GCC/Clang: Use -fuse-ld=gold or -fuse-ld=lld for better incremental linking
        target_link_options(${TARGET} PRIVATE
            $<$<CONFIG:Debug>:-Wl,--incremental>
        )
    elseif(CMAKE_C_COMPILER_ID MATCHES "MSVC")
        # MSVC: Use /INCREMENTAL
        target_link_options(${TARGET} PRIVATE
            $<$<CONFIG:Debug>:/INCREMENTAL>
        )
    endif()

    # Set target property
    set_target_properties(${TARGET} PROPERTIES
        NEXUS_INCREMENTAL_LINKING ON
    )

    message(STATUS "Enabled incremental linking for: ${TARGET}")
endfunction()

##############################################################################
# Utility Functions
##############################################################################

#
# Print dependency graph for target
# TARGET: Target name
#
function(nexus_print_dependency_graph TARGET)
    # Build dependency graph
    nexus_build_dependency_graph(${TARGET} GRAPH_JSON)

    message(STATUS "Dependency graph for ${TARGET}:")
    message(STATUS "${GRAPH_JSON}")
endfunction()

#
# Get incremental build statistics
# TARGET: Target name
#
function(nexus_print_incremental_stats TARGET)
    # Get total sources
    get_target_property(SOURCES ${TARGET} SOURCES)
    list(LENGTH SOURCES TOTAL_SOURCES)

    # Get sources that need rebuild
    nexus_get_sources_to_rebuild(${TARGET} REBUILD_SOURCES)
    list(LENGTH REBUILD_SOURCES REBUILD_COUNT)

    # Calculate percentage
    if(TOTAL_SOURCES GREATER 0)
        math(EXPR SKIP_COUNT "${TOTAL_SOURCES} - ${REBUILD_COUNT}")
        math(EXPR SKIP_PERCENT "(${SKIP_COUNT} * 100) / ${TOTAL_SOURCES}")
    else()
        set(SKIP_PERCENT 0)
    endif()

    message(STATUS "Incremental build stats for ${TARGET}:")
    message(STATUS "  Total sources: ${TOTAL_SOURCES}")
    message(STATUS "  Need rebuild: ${REBUILD_COUNT}")
    message(STATUS "  Can skip: ${SKIP_COUNT} (${SKIP_PERCENT}%)")
endfunction()

