include_guard(GLOBAL)
function(nexus_add_application)
    cmake_parse_arguments(APP "" "TARGET;VERSION" "SOURCES;EXTRA_DEPS;PLATFORM_DEPS" ${ARGN})
    if(APP_UNPARSED_ARGUMENTS OR NOT APP_TARGET OR NOT APP_SOURCES)
        message(FATAL_ERROR "nexus_add_application requires TARGET, SOURCES and known arguments")
    endif()
    set(platform_target "platform_${NEXUS_PLATFORM}")
    if(NOT TARGET "${platform_target}")
        message(FATAL_ERROR "Application ${APP_TARGET} requires selected platform target ${platform_target}")
    endif()
    if(NEXUS_PLATFORM STREQUAL "stm32")
        get_target_property(platform_type "${platform_target}" TYPE)
        get_target_property(startup_source "${platform_target}" NEXUS_STARTUP_SOURCE)
        get_target_property(linker_script "${platform_target}" NEXUS_LINKER_SCRIPT)
        foreach(input startup_source linker_script)
            if(NOT ${input} OR NOT IS_ABSOLUTE "${${input}}" OR
               NOT EXISTS "${${input}}" OR IS_DIRECTORY "${${input}}")
                message(FATAL_ERROR "${platform_target} requires an existing absolute ${input} property")
            endif()
        endforeach()
        get_target_property(platform_sources "${platform_target}" SOURCES)
        if(NOT platform_type STREQUAL "OBJECT_LIBRARY" OR NOT startup_source IN_LIST platform_sources)
            message(FATAL_ERROR "${platform_target} must compile its declared startup_source into platform objects")
        endif()
    endif()
    add_executable(${APP_TARGET} ${APP_SOURCES})
    if(APP_VERSION)
        target_compile_definitions(${APP_TARGET} PRIVATE "NEXUS_APP_VERSION=\"${APP_VERSION}\"")
    endif()
    target_link_libraries(${APP_TARGET} PRIVATE "${platform_target}" hal osal ${APP_EXTRA_DEPS} ${APP_PLATFORM_DEPS})
    if(NEXUS_PLATFORM STREQUAL "native" AND CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_link_options(${APP_TARGET} PRIVATE "-Wl,-Map,${CMAKE_BINARY_DIR}/bin/${APP_TARGET}.map")
    endif()
    if(NEXUS_PLATFORM STREQUAL "stm32")
        set_target_properties(${APP_TARGET} PROPERTIES SUFFIX ".elf")
        target_link_options(${APP_TARGET} PRIVATE
            "-Wl,-Map,${CMAKE_BINARY_DIR}/bin/${APP_TARGET}.map"
            "-Wl,--defsym,_Min_Stack_Size=${CONFIG_APP_STACK_SIZE}"
            "-Wl,--defsym,_Min_Heap_Size=${CONFIG_APP_HEAP_SIZE}")
        if(CONFIG_APP_PRINT_MEMORY_USAGE)
            target_link_options(${APP_TARGET} PRIVATE -Wl,--print-memory-usage)
        endif()
        if(CONFIG_APP_GENERATE_BIN)
            add_custom_command(TARGET ${APP_TARGET} POST_BUILD
                COMMAND "${CMAKE_OBJCOPY}" -O binary "$<TARGET_FILE:${APP_TARGET}>" "${CMAKE_BINARY_DIR}/bin/${APP_TARGET}.bin" VERBATIM)
        endif()
        if(CONFIG_APP_GENERATE_HEX)
            add_custom_command(TARGET ${APP_TARGET} POST_BUILD
                COMMAND "${CMAKE_OBJCOPY}" -O ihex "$<TARGET_FILE:${APP_TARGET}>" "${CMAKE_BINARY_DIR}/bin/${APP_TARGET}.hex" VERBATIM)
        endif()
        if(CONFIG_APP_PRINT_SIZE)
            add_custom_command(TARGET ${APP_TARGET} POST_BUILD
                COMMAND "${CMAKE_SIZE}" "$<TARGET_FILE:${APP_TARGET}>" VERBATIM)
        endif()
    endif()
endfunction()
