include_guard(GLOBAL)

# Board selection has one external path. The manifest records hardware only;
# software features remain in the effective Kconfig fragment.
macro(nexus_prepare_board)
    set(_nexus_board_name "")
    if(NEXUS_BOARD_DIR)
        get_filename_component(NEXUS_BOARD_DIR "${NEXUS_BOARD_DIR}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        if(NOT EXISTS "${NEXUS_BOARD_DIR}/board.json")
            message(FATAL_ERROR "NEXUS_BOARD_DIR requires board.json")
        endif()
        file(READ "${NEXUS_BOARD_DIR}/board.json" _nexus_board_manifest)
        string(JSON _nexus_board_name ERROR_VARIABLE _nexus_board_error GET "${_nexus_board_manifest}" id)
        if(_nexus_board_error OR NOT _nexus_board_name MATCHES "^[a-z][a-z0-9_-]+$")
            message(FATAL_ERROR "External Board manifest requires a valid id")
        endif()
    endif()
    set(ENV{NEXUS_EXTERNAL_BOARD_NAME} "${_nexus_board_name}")
endmacro()

macro(nexus_configure_board)
    if(CONFIG_BOARD_EXTERNAL)
        if(NOT NEXUS_BOARD_DIR)
            message(FATAL_ERROR "BOARD_EXTERNAL requires NEXUS_BOARD_DIR")
        endif()
        set(NEXUS_SELECTED_BOARD_DIR "${NEXUS_BOARD_DIR}")
    else()
        if(NEXUS_BOARD_DIR)
            message(FATAL_ERROR "External Board selection/effective configuration conflict")
        endif()
        foreach(_nexus_pair "BOARD_NATIVE_REFERENCE;native_reference" "BOARD_STM32F4DISCOVERY;stm32f4discovery"
                "BOARD_STM32F407_QIMING_V31;stm32f407_qiming_v31"
                "BOARD_STM32F407VE_SKY_QINGCHUN;stm32f407ve_sky_qingchun"
                "BOARD_GD32F470_LIANGSHAN;gd32f470_liangshan")
            list(GET _nexus_pair 0 _nexus_symbol)
            list(GET _nexus_pair 1 _nexus_directory)
            if(CONFIG_${_nexus_symbol})
                set(NEXUS_SELECTED_BOARD_DIR "${NEXUS_SOURCE_DIR}/boards/${_nexus_directory}")
            endif()
        endforeach()
    endif()
    if(NOT NEXUS_SELECTED_BOARD_DIR)
        message(FATAL_ERROR "A maintained or external Board is required")
    endif()
    set(_nexus_layout_argument)
    if(NEXUS_FLASH_LAYOUT_FILE)
        get_filename_component(NEXUS_FLASH_LAYOUT_FILE "${NEXUS_FLASH_LAYOUT_FILE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        list(APPEND _nexus_layout_argument --layout "${NEXUS_FLASH_LAYOUT_FILE}")
    endif()
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${NEXUS_SOURCE_DIR}/scripts/configure/board_package.py"
        --board-dir "${NEXUS_SELECTED_BOARD_DIR}" --config "${NEXUS_CONFIG_DIR}/effective.config"
        --output-dir "${NEXUS_CONFIG_DIR}" --sdk-root "${NEXUS_SOURCE_DIR}" ${_nexus_layout_argument}
        RESULT_VARIABLE _nexus_board_result ERROR_VARIABLE _nexus_board_diagnostic)
    if(NOT _nexus_board_result EQUAL 0)
        message(FATAL_ERROR "${_nexus_board_diagnostic}")
    endif()
    include("${NEXUS_CONFIG_DIR}/board.cmake")
    if(NOT CONFIG_BOARD_NAME STREQUAL NEXUS_BOARD_NAME)
        message(FATAL_ERROR "Board identity/effective configuration mismatch")
    endif()
    file(GLOB_RECURSE _nexus_board_inputs CONFIGURE_DEPENDS "${NEXUS_SELECTED_BOARD_DIR}/*")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_nexus_board_inputs}
        "${NEXUS_SOURCE_DIR}/scripts/configure/board_package.py" "${NEXUS_FLASH_LAYOUT_FILE}")
endmacro()

# Called only after the selected private vendor SDK targets exist.
macro(nexus_add_selected_board)
    add_subdirectory("${NEXUS_SELECTED_BOARD_DIR}" "${NEXUS_BINARY_DIR}/board")
    if(NOT TARGET "${NEXUS_BOARD_TARGET}")
        message(FATAL_ERROR "Board package did not define ${NEXUS_BOARD_TARGET}")
    endif()
    foreach(_nexus_object IN LISTS NEXUS_BOARD_OBJECT_TARGETS)
        if(NOT TARGET "${_nexus_object}")
            message(FATAL_ERROR "Board package did not define ${_nexus_object}")
        endif()
        get_target_property(_nexus_object_type "${_nexus_object}" TYPE)
        if(_nexus_object_type STREQUAL "OBJECT_LIBRARY")
            # Every compiled Board-owned file must be in its hashed input set.
            file(READ "${NEXUS_SELECTED_BOARD_DIR}/board.json" _nexus_manifest_text)
            string(JSON _nexus_input_count LENGTH "${_nexus_manifest_text}" inputs)
            math(EXPR _nexus_input_last "${_nexus_input_count} - 1")
            set(_nexus_owned_inputs)
            foreach(_nexus_index RANGE 0 ${_nexus_input_last})
                string(JSON _nexus_input GET "${_nexus_manifest_text}" inputs ${_nexus_index})
                get_filename_component(_nexus_input "${NEXUS_SELECTED_BOARD_DIR}/${_nexus_input}" REALPATH)
                list(APPEND _nexus_owned_inputs "${_nexus_input}")
            endforeach()
            get_target_property(_nexus_sources "${_nexus_object}" SOURCES)
            get_target_property(_nexus_source_dir "${_nexus_object}" SOURCE_DIR)
            foreach(_nexus_source IN LISTS _nexus_sources)
                get_filename_component(_nexus_source "${_nexus_source}" REALPATH BASE_DIR "${_nexus_source_dir}")
                if(NOT _nexus_source IN_LIST _nexus_owned_inputs)
                    message(FATAL_ERROR "Board target ${_nexus_object} source is not manifest-bound: ${_nexus_source}")
                endif()
            endforeach()
            list(APPEND component_objects "${_nexus_object}")
        elseif(NOT _nexus_object_type STREQUAL "INTERFACE_LIBRARY")
            message(FATAL_ERROR "Board wiring must use OBJECT or INTERFACE targets")
        endif()
    endforeach()
endmacro()
